### ISSUE TITLE
Bitdefender identifies update.exe as virus

### ISSUE THREAD

**Issue by genesismonkey** [Haato3o/HunterPie#135]
I'm running HunterPie 1.0.4, and this evening Bitdefender quarantined Update.exe as Gen:Variant.Ursu.818982. This has not happened before when running HunterPie. After the removal of Update.exe, HunterPie is able to start with [ERROR] Failed to update HunterPie. Check if you're connected to the internet.

Is this an issue with the antivirus suddenly being more aggressive? Has anyone encountered something similar? Has HunterPie's update mechanism been compromised somehow?

**Comment by Haato3o** [comment]
Some antiviruses may detect it as virus, probably because it downloads files from the internet, but that's the only reason I can think of that would cause a false positive. But no, it is not a virus (in fact, it's completely open source [here](https://github.com/Haato3o/HunterPie/tree/master/Update)) and has not been compromised. Just add an exception to HunterPie's folder and it should be okay.

**Comment by genesismonkey** [comment]
Ok, it just changed this evening when it had previously not been an issue with bitdefender. I wanted to bring it up just in case. I guess you can add that Bitdefender is known to give a false positive.
