### ISSUE TITLE
[Error]Monster Widget Part health bar formats

### ISSUE THREAD

**Issue by MrPickled** [Haato3o/HunterPie#162]
Monster Widget Part health bar formats has a error.We can't see the current health by
 useing the setting:{Current}/{Max}.I think maybe the part of "{Current}" can't read the game data correctly.Thank for you read and fix.

**Comment by Haato3o** [comment]
I don't really understand what you're reporting exactly, but I assume it's the part current health displaying as 0, that's **NOT** a bug and it is working as intended, the game has limitations for when you're not party leader. Only host has the actual part information and that's not something I can fix because it's a game limitation and it's how Capcom coded the game.

If that's not the issue, please give me more details and maybe screenshots so I can understand what's the problem here.
