### ISSUE TITLE
Something is blocking Hunterpie native to create a socket.

### ISSUE THREAD

**Issue by TardyTech** [Haato3o/HunterPie#163]
While HunterPie itself is working fine, all the plugins don't work at all. I've added it and the game to the firewall exceptions but it didn't help. I've even turned it off completely, but it didn't help either

**Comment by Haato3o** [comment]
I mean, you pretty much said what the issue is in the title, a socket not being created could have millions of different reasons, maybe your port is blocked, maybe something is blocking it, maybe it failed when trying to create the socket for whatever reason. Maybe the reason isn't even the server socket, maybe something is blocking the client, maybe the socket is dying too soon, I don't know, It's impossible to tell what the error is without any information.

**Comment by TardyTech** [comment]
Will the screenshot help? 
![image](https://user-images.githubusercontent.com/84504472/119053418-b66e1000-b9ce-11eb-9d9b-15076b7ac0de.png)

**Comment by Haato3o** [comment]
No, that's just a generic error message from C#, it doesn't help because the error isn't coming out from the C# client, it's from the native part, which is just hard to debug unless you do it yourself by compiling the project as debug and running it so it will create a console when injecting the native into the game. It's a local problem, so not much I can do since I can't reproduce it.

**Comment by TardyTech** [comment]
So i was able to fix it by relocating the HunterPie folder. Idk why it helped but it did
