### ISSUE TITLE
HunterPie causes game crash after MHWI update 15.11.01 today

### ISSUE THREAD

**Issue by ingrid-z** [Haato3o/HunterPie#165]
Player is able to login into the game normally.
Then wait for only few secs(10~20ish), game crash and exit to desktop.

I like this mod, thanks for your hard work.

**Comment by AlucedIcen** [comment]
Hunterpie isn't at fault, the update broke Stracker's Loader. The temporary fix before Stracker updates his mod is to rename the dtdata.dll to hid.dll in the game's exe folder. Some mods may not work for the time being!

**Comment by OZIZI021** [comment]
Thanks for the fix ... But when I played MHWI using only Hunterpie and Stracker's Loader and it crashed. On the other hand, when I played MHWI with some mods except Hunterpie and Stracker's Loader, it did not crash.So I think it's caused by Hunterpie.

**Comment by Haato3o** [comment]
> Thanks for the fix ... But when I played MHWI using only Hunterpie and Stracker's Loader and it crashed. On the other hand, when I played MHWI with some mods except Hunterpie and Stracker's Loader, it did not crash.So I think it's caused by Hunterpie.

The reason for the crash is more complex than that, HunterPie requires CRCBypass to hook in-game functions for some of the native features, CRCBypass requires Stracker's loader to be loaded since it loads all the plugins. Right now, Stracker's isn't getting loaded because the game doesn't load `dtdata.dll` by default anymore, however, having it in your game folder makes HunterPie assume you have Strackers (this is a check to avoid creating detours when you don't have strackers) and it enables the native features. 
Since Stracker's not getting loaded anymore and HunterPie thinks it is, then it creates the detour and CRC forces the game to crash because that's the job of CRC. In short, the crash itself is caused by CRC because CRCBypass isn't loaded because stracker isn't loaded either, it's not exactly HunterPie's fault because any plugin that detours function would still make your game crash.
