### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by gamer4eg** [Haato3o/HunterPie#56]
I immediately apologize for the text generated by the Google translator.

List of offers:

1) Ammo counter widget for LBG / HBG

2) Support for launching two application windows (I play on a PC divided through aster program for two simultaneously working users)

PS Ready to test work in 2 windows. Now for such work you have to run one of the windows in the sandboxie. But in this mode, hotkeys do not work.

**Comment by Haato3o** [comment]
1 - There is already a capture indicator which is way more visible than a flashing animation, it appears on top right of the monster health bar and it's a trap icon.
![example](https://cdn.discordapp.com/attachments/402557384209203200/707641901658013726/unknown.png)

2 - That's going in the class helper widget that is already in development, I've finished the Insect Glaive and Charge Blade so far. Since it takes some time to gather information from memory and understand how it works, design a widget, code the widget logic, I'll be done (hopefully) by next week. Feel free to join Discord if you want to see the work-in-progress of the new widget: https://discord.gg/5pdDq4Q

3 - Not sure why you'd want two instances of HunterPie since they would hook to the same game (the first game process), and consequently show the exact same data.

**Comment by gamer4eg** [comment]
2game. 2 users 1pc
https://www.ibik.ru/
2steam work in sandboxie
![image](https://user-images.githubusercontent.com/23147230/81209632-74e41000-8fd9-11ea-93dd-1e0fdb118fd1.png)

**Comment by gamer4eg** [comment]
Oftop: And so that the PC copes with two users, it looks like this ... =)
Just assembling one such pc is cheaper than two with the same overall performance.
![image](https://user-images.githubusercontent.com/23147230/81209841-b2e13400-8fd9-11ea-9739-ea00dc86fde0.png)

**Comment by gamer4eg** [comment]
I am ready to test.
I am ready to give access to the PC through TeamViewer.
It is not convenient to use the program when running in sandboxie.
You also need to select a discord process for integration.
To save your time, the easiest way is to add this to the arguments of the .exe call.

**Comment by gamer4eg** [comment]
![image](https://user-images.githubusercontent.com/23147230/81225725-5d655100-8ff2-11ea-8b18-24398f6fa0d0.png)

**Comment by Haato3o** [comment]
The problem is that it isn't that simple, HunterPie gets the first MHW process to read it's memory. Right now, if you open two HunterPies and two MHW, both HunterPie instances will read the first MHW process and display the same information. So what I need to do is:

1 - Find a way to detect which MonsterHunterWorld process the first instance of HunterPie is hooked to;
2 - Hook the second instance of HunterPie to the next process in the process list;

I'm also busy with something else for probably this whole week, so I can't start working on this yet.
Also, you can't just select the Discord that you want to connect to, that's handled by the Discord RPC library, not by HunterPie.

**Comment by gamer4eg** [comment]
They are launched from different users.
Well, or the second option is the selection menu.
But I almost managed to get the program to work correctly in a partially isolated environment.

**Comment by gamer4eg** [comment]
I would be glad to see a hint why the program cannot access the keys when starting up in the sandboxie.

**Comment by Haato3o** [comment]
> I would be glad to see a hint why the program cannot access the keys when starting up in the sandboxie.

HunterPie uses the [https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey](RegisterHotKey) function from the Windows API to register it's hotkeys. If it's failing to register them then there are two reasons I can think of:
Either Sandboxie doens't support it, or HunterPie is trying to register an already registered Hotkey (you can try setting the hotkey to something else and see if it still fails to register it)

**Comment by gamer4eg** [comment]
=(
https://github.com/sandboxie/sandboxie/issues/17
