### ISSUE TITLE
[Suggestion] Share part health info and status buildups via discord join feature

### ISSUE THREAD

**Issue by ajc-developer** [Haato3o/HunterPie#59]
The overlay is great by the way but I was discussing some things with friends about how only the host can see part info.  In a way similar to [Runelite's ](https://github.com/runelite) feature (Oldschool runescape), information about monster parts and status effects could be shared from the host to other clients using the discord join feature.

Thanks for all of the work you put in to the overlay!

**Comment by Haato3o** [comment]
You can't do that with the join feature, when you click the "Ask To Join" button, it sends an event to HunterPie, HunterPie answers with a session ID (if you accept the request), Discord sends that session ID to the person who requested to join and their HunterPie opens the session for them. It only happens once so it's not like I can continuously send information to Discord for it to distribute to other people in the party. Spamming the button "Ask To Join" doesn't work either, since Discord has a built-in cooldown system for that feature.
