### ISSUE TITLE
[Suggestion] Allow an "auto game launch option"

### ISSUE THREAD

**Issue by Afflicti0n** [Haato3o/HunterPie#63]
Allow an Auto game launch option to hunterpie on start up, would allow for vortex to treat this as a game extension tool without having to manually script a launch event.

**Comment by Haato3o** [comment]
Auto launching a program when another program starts isn't that easy, it requires DLL injection and that's not something I'm willing to do at the moment since I don't have much knowledge on it. An alternative for that would be to just use the already existing exe launchers: 
https://www.nexusmods.com/monsterhunterworld/mods/2477
