### ISSUE TITLE
Hud overlay Not showing

### ISSUE THREAD

**Issue by AivcJoe** [Haato3o/HunterPie#65]
So I'm not sure if its on my end or if its the overlays end but when ever i go into group fights with my friends the hud stops working entirely as if im not even running it, and on a side note it was running yesterday while playing with them but no monster parts were showing up so i could tell if parts where going to break or not

**Comment by Haato3o** [comment]
>  when ever i go into group fights with my friends the hud stops working entirely as if im not even running it

Not sure if you mean that only the monster widget and damage don't work properly when you play with friends or if the whole overlay (including abnormalities tracker, mantle tracker and class helper) stops working. Playing multiplayer does not affect those listed in the parenthesis, but it **does** affect the monster widget.

Consider reading the [FAQ](https://github.com/Haato3o/HunterPie/wiki/FAQ): 

>**I can't see monster parts**
Due to how the game works, only the quest host can see the monster parts health while the other party members only have access to the flinch/break counter.
---
>**My damage meter is not working**
The game doesn't store player's damage in memory when you're in offline mode, in expedition/guiding lands or in certain quests (e.g: Zorah Magdaros's and Kulve Taroth's quest). It also doesn't store damages that your party have done to monsters that aren't part of your quest objective.

If your abnormalities tray doesn't work, then make sure you have the abnormalities you want to track enabled. The documentation for the abnormalities tray can be found [here](https://github.com/Haato3o/HunterPie/wiki/Abnormalities-Tray#choosing-the-abnormalities-you-want).
