### ISSUE TITLE
Inaccurate Switch Axe Power Phial Charge level for for Class Helper Widget

### ISSUE THREAD

**Issue by zerenx** [Haato3o/HunterPie#95]
When using a Power Phial for Switch Axe, the charge level in the Class Helper Widget needs to be around 121% before it gets to Sword Amp mode.

But when using Exhaust or Power Element Phial, it's more or less correct, needing only 100% (more or less) to reach Sword Amp mode

Is this an intended behaviour (because Power Phials do need more hits to fully charge it)?
![2020-08-14 17_37_00-Greenshot](https://user-images.githubusercontent.com/8742814/90241663-b5afb880-de55-11ea-8e37-c70ce3055ff9.png)

**Comment by Haato3o** [comment]
Each phial is different and requires an specific charge % to activate the sword amp mode, the reason why the game shows the sword border as ~80% and HunterPie shows 112% is because the value in memory is 1.12, but the game knows what phial you're using, so it just changes the maximum charge required to show a valid percentage, but HunterPie can't track it, at least not yet.

**Comment by zerenx** [comment]
Yes, I realize different Switch Axe Phials need different charge level to activate Sword Amp mode. 
Power Phials being the one that needs the most.

But if this is the intended behavior, may I suggest to remove the percentage sign?
Because when people see the percentage sign, they will assume Sword Amp Mode will activate at 100%, which it doesn't always

**Comment by Haato3o** [comment]
No, the only difference that would make is that it would appear as 120 instead of 120%. But then it would cause even more confusion, 120 what? Seconds? Power? This way we at least know Power phials requires 20% more power to fully charge.

**Comment by zerenx** [comment]
I defer to your judgement about the displayed number
